name: CI

on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv pip install --system tox tox-uv

    - name: Install Ghostscript
      run: |
        # From binary on https://www.ghostscript.com/download/gsdnld.html
        wget --quiet https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10040/gs_10.04.0_amd64_snap.tgz
        tar xvf gs_10.04.0_amd64_snap.tgz
        sudo snap install --devmode gs_10.04.0_amd64_snap/gs_10.04.0_amd64.snap

    - name: Run tox targets for ${{ matrix.python-version }}
      run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

  release:
    needs: [tests]
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    environment: release

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Build
        run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
